CREATE TABLE CUSTOMER (
    CUST_NO    NUMBER(4)    CONSTRAINT pk_customer PRIMARY KEY,
    FIRST_NAME VARCHAR2(20) NOT NULL,
    LAST_NAME  VARCHAR2(20),
    ADDRESS    VARCHAR2(20),
    CITY       VARCHAR2(8),
    STATE      VARCHAR2(20),
    PIN        NUMBER(6),
    B_DATE     DATE,
    STATUS     CHAR(1)      CONSTRAINT chk_status CHECK (STATUS IN ('V','I','A'))
);
 
-- ─── INSERT DATA ─────────────────────────────────────────────
 
INSERT INTO CUSTOMER VALUES (1003,'RAJ',   'BAHADUR','SHANTI VILLA','UDP','KARNATAKA',576101,TO_DATE('1-AUG-70','DD-MON-YY'),'V');
INSERT INTO CUSTOMER VALUES (1004,'FELIX', 'SIMON',  'M-J-56',     'PJM','GOA',      403002,TO_DATE('12-FEB-71','DD-MON-YY'),'A');
INSERT INTO CUSTOMER VALUES (1005,'RAJAN', 'KUTTY',  'A1 TRADERS', 'KNR','KERALA',   670001,TO_DATE('09-JUN-71','DD-MON-YY'),'A');
INSERT INTO CUSTOMER VALUES (1006,'SHILPA','PAI',    '12/4B',      'MNG','KARNATAKA',574154,TO_DATE('11-DEC-70','DD-MON-YY'),'I');
INSERT INTO CUSTOMER VALUES (1007,'BOSCO', 'RAKSHIT','R.K. PLAZA', 'BNG','KARNATAKA',576201,TO_DATE('01-JAN-71','DD-MON-YY'),'A');
 
COMMIT;
 
-- ─── QUERIES ─────────────────────────────────────────────────
 
-- Q3. All records
SELECT * FROM CUSTOMER;
 
-- Q4. Records where state = KARNATAKA
SELECT * FROM CUSTOMER WHERE STATE = 'KARNATAKA';
 
-- Q5. Delete row where PIN = 576201
DELETE FROM CUSTOMER WHERE PIN = 576201;
COMMIT;
 
-- Q6. Update PIN = 476001 where CUST_NO = 1004
UPDATE CUSTOMER SET PIN = 476001 WHERE CUST_NO = 1004;
COMMIT;
 
-- Q7. Change address and pin for CUST_NO = 1003
UPDATE CUSTOMER
SET ADDRESS = 'KAVI MUDDANNA MARG', PIN = 576104
WHERE CUST_NO = 1003;
COMMIT;
 
-- Q8. Delete GOA records then retrieve all records
DELETE FROM CUSTOMER WHERE STATE = 'GOA';
COMMIT;
-- ROLLBACK to get them back:
ROLLBACK;
SELECT * FROM CUSTOMER;
 
-- Q9. Invalid ('I') persons
SELECT * FROM CUSTOMER WHERE STATUS = 'I';
 
-- Q10. Distinct states
SELECT DISTINCT STATE FROM CUSTOMER;
 
-- Q11. Sort by state alphabetically
SELECT * FROM CUSTOMER ORDER BY STATE ASC;
 
-- Q12. Sort state in descending order
SELECT * FROM CUSTOMER ORDER BY STATE DESC;
 
-- Q13. Karnataka customers who are valid ('V')
SELECT * FROM CUSTOMER WHERE STATE = 'KARNATAKA' AND STATUS = 'V';
 
-- Q14. Karnataka or Kerala customers
SELECT * FROM CUSTOMER WHERE STATE IN ('KARNATAKA','KERALA');
 
-- Q15. Karnataka or Kerala customers who are ACTIVE ('A')
SELECT * FROM CUSTOMER WHERE STATE IN ('KARNATAKA','KERALA') AND STATUS = 'A';
 
-- Q16. Karnataka customers with pin 576201
SELECT * FROM CUSTOMER WHERE STATE = 'KARNATAKA' AND PIN = 576201;
 
-- Q17. All rows except CUST_NO = 1005
SELECT * FROM CUSTOMER WHERE CUST_NO != 1005;
 
-- Q18. State begins with 'K' followed by any character
SELECT * FROM CUSTOMER WHERE STATE LIKE 'K%';
 
-- Q19. Name contains 'RAJ'
SELECT * FROM CUSTOMER WHERE FIRST_NAME LIKE '%RAJ%';
 
-- Q20. CUST_NO in range 1003 to 1005
SELECT * FROM CUSTOMER WHERE CUST_NO BETWEEN 1003 AND 1005;
 
-- Q21. Dates in range 10-JAN-71 to 31-DEC-71
SELECT * FROM CUSTOMER
WHERE B_DATE BETWEEN TO_DATE('10-JAN-71','DD-MON-YY')
                 AND TO_DATE('31-DEC-71','DD-MON-YY');
 
-- Q22. City = UDP, MNG, BNG or PGN
SELECT * FROM CUSTOMER WHERE CITY IN ('UDP','MNG','BNG','PGN');
 
-- Q23. Rename CUSTOMER to CUST
RENAME CUSTOMER TO CUST;